### PR TITLE
Redux implementation

### PR DESCRIPTION
**Pull request by syedsaadh**
Refactoring the architecture as per react redux data flow 
Data Flow

### CODE REVIEW

**Comment by imujjwal96** [comment]
image
What's this?
Also, I am not able to type in the inputs

**Comment by syedsaadh** [comment]
Thats Debug tool for debugging states. Will not be in Production
And Not able to change email part will remove that @imujjwal96

**Comment by syedsaadh** [comment]
@imujjwal96 Solved the input issue

**Review by imujjwal96 — APPROVED** [review]
Tested, works!

**Pull request merged**
